export const UPLOAD_REQUEST = 'UPLOAD_REQUEST';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILURE = 'UPLOAD_FAILURE';

export const GET_HOMEPAGE_POSTS_REQUEST = 'GET_HOMEPAGE_POSTS_REQUEST';
export const GET_HOMEPAGE_POSTS_SUCCESS = 'GET_HOMEPAGE_POSTS_SUCCESS';
export const GET_HOMEPAGE_POSTS_FAILURE = 'GET_HOMEPAGE_POSTS_FAILURE';

export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAILURE = 'LIKE_POST_FAILURE';

export const GET_USERS_POSTS_REQUEST = 'GET_USERS_POSTS_REQUEST';
export const GET_USERS_POSTS_SUCCESS = 'GET_USERS_POSTS_SUCCESS';
export const GET_USERS_POSTS_FAILURE = 'GET_USERS_POSTS_FAILURE';