export const SET_STOMP_CLIENT_REQUEST = 'SET_STOMP_CLIENT_REQUEST';
export const SET_STOMP_CLIENT_SUCCESS = 'SET_STOMP_CLIENT_SUCCESS';
export const SET_STOMP_CLIENT_FAILURE = 'SET_STOMP_CLIENT_FAILURE';